### ISSUE TITLE
Snapshot from HLS or WebRTC video

### ISSUE THREAD

**Issue by fischer-felix** [cmuche/octoprint-timelapseplus#30] opened 2023-04-27 20:26 UTC
Hi, I have replaced the default MJPEG streamer with go2rtc, which allows me to use HLS and/or WebRTC to stream the video (especially for checking when I'm not home, since otherwise the bandwidth required is too high).
The only issue with this is, that go2rtc does not provide a jpg snapshot url (at least not without some extra transcoding, wich I can't do on my pi).

Would it be possible to get still frames from an HLS or WebRTC stream?

**Comment by cmuche** [comment] 2023-04-27 21:38
Hi @fischer-felix
Thanks for your input! I'll mark this as a feature request and hope i can get on that topic soon and be able to test it properly. But is there ANY possibility to get a snapshot (=still image) from go2rtc? Just looked up the documentation and it should be possible (couldn't verify just now) - not necessarily as a jpg, but maybe other formats? Otherwise I'd have to implement the snapshot generation from video stream manually.

**Comment by fischer-felix** [comment] 2023-04-27 22:03
There is a frame.mp4 option, which one singular h264/h265 frame, however I will do some testing if there isn't some delay like on the hls stream.

**Comment by cmuche** [comment] 2023-04-28 09:12
Okay, please let me know what your results are. I'll have a look at HLS- and WebRTC streams.

**Comment by AlexxIT** [comment] 2023-04-28 17:07
You can't get JPEG from H264/H265 without transcoding.
That's why go2rtc provide frame.mp4
It cost nothing for CPU

**Comment by cmuche** [comment] 2023-04-29 00:10
Okay, then this would have to happen on Timelapse+ directly. I'll play around with go2rtc and see what I can get out of it.

**Comment by cmuche** [comment] 2023-05-08 22:04
Hi @fischer-felix 
I did some investigation, reading, coding etc. and now came up with a first solution.
Timelapse+ should now be able to use mutiple types of webcam input: MP4/HLS/MJPEG streams directly as well as the good old JPG snapshots. Before I release it with the 1.2.0 version I would like to confirm that it works in a real environment like yours since my testing capabilities with my local go2rtc installation are limited to my hardware setup (webcam etc.). Therefore I would like to ask you if you could install this version manually on your Octoprint setup and verify if it works as intended: https://github.com/cmuche/octoprint-timelapseplus/archive/refs/heads/30-snapshot-from-hls-or-webrtc-video.zip
You will have a dropdown menu in the settings where you set the webcam URL as well. I really hope this works and fixes your issues with Timelapse+.
Greetings and thank you in advance!

**Comment by fischer-felix** [comment] 2023-05-08 22:14
Excuse the recent inactivity, there's been quite a lot going on, but I'll get around to testing it as soon as possible.

**Comment by cmuche** [comment] 2023-05-08 22:34
Hi! Sure - no stress ;-) I'm grateful at all for your input!

**Comment by fischer-felix** [comment] 2023-05-09 13:52
Tried it on a relatively short print today, and the good news is, that it works!
It does, however, report somewhere around 2000ms latency when taking a snapshot, which is why I only tried it in time based mode and set it to shoot every 15s.
The print went smoothly, and all the snapshots were captured and saved as .jpg (they do look a bit compressed, however quality wouldn't be my first concern).
Rendering is when I ran into an issue:
It starts fine, however the progress bar gets stuck at around 48% after which the render fails saying "Render Job failed" "Failed to run FFmpeg (Return Code -9).
Start:
![Screenshot_2023 05 09_15:40:33_cropped](https://github.com/cmuche/octoprint-timelapseplus/assets/65448408/ef85e317-edf1-4d56-88e1-dd52eef6cba3)
I did a try while looking at htop on the pi, and it seems like it just keeps spawning instances of FFmpeg, as in the beginning there was only one FFmpeg process in htop, while at the end there were 8.

Start:
![Screenshot_2023 05 09_15:39:53](https://github.com/cmuche/octoprint-timelapseplus/assets/65448408/6e4f4a2f-2563-4e2c-935d-1cf2c328e66e)
End:
![Screenshot_2023 05 09_15:40:14](https://github.com/cmuche/octoprint-timelapseplus/assets/65448408/920c04bc-7343-47bf-8ca6-d0e87c3d7a63)

Is this supposed to be that way?

**Comment by cmuche** [comment] 2023-05-09 15:07
Hi @fischer-felix 
Great to hear that the capturing works and thank you for your information! 👍 Even if 2000ms are an insane time to capture. But I think I can't really optimize this since the transcoding is done by FFmpeg itself.

But the rendering issues don't look good. I assume that your memory just runs out (the memory and swap is full on your screenshots). Encoding is pretty expensive and return code -9 imho also indicates that. As I can see you are using the HQ format preset for H264. Does it also occur when using the 'Draft Quality' preset? It should be way more memory efficient since it doesn't compress that much and has lower quality. Could be a good starting point if it works with that. I guess I'll have to work a bit the rendering pipeline optimization. I'll also dig out my Raspberry and experiment a bit with that.

**Comment by cmuche** [comment] 2023-05-09 16:21
Okay - that's a good sign it's rendering at Draft Quality. Sure - it's not really usable that way. But it seems like FFmpeg is indeed running out of memory with the other options.

At the moment I can think of 2 possible solutions:

1. Introducing 'Low Memory' format presets. The compression flags could be the crucial point here thar cause FFmpeg to consume that much memory. But using faster compression presets would lead to bigger file sizes. I'll test and try if this is a suitable solution on my Pi.
2. Functionality to upload Frame Collections: Unfortunately the rendering pipeline is not a single FFmpeg call. The enhancements are not done by FFmpeg at all and some formats need 2-phase renderung and encoding. You can already download Frame Collections so it would be possible to upload those to a beefier OctoPrint host and render it there.

Just one more question: Did you observe the crashes in the 'Rendering' or 'Encoding' phase?

I'll do some more investigation in this topic an keep you updated. 👍 Thank you once again for your help so far!

**Comment by fischer-felix** [comment] 2023-05-09 21:05
Quick update: When testing in which phase it fails, I just noticed that for whatever reason, the (I believe) low quality preset actually finished encoding, so it was just the web interface that restarted while FFmpeg was still running.
This one actually produces somewhat useable quality, so that's a nice surprise.

Anyway, it does fail during the 'Encoding' phase, 'Rendering' is actually really fast (comparatively), even on the HQ preset.

**Comment by cmuche** [comment] 2023-05-11 07:54
Short Note: Downloading/Uploading Frame Collections is done and will also be released in the 1.2.0.

**Comment by fischer-felix** [comment] 2023-05-24 14:43
Thanks for all the work on this! 
I tried verson 1.2.2 on a medium lenght print (~1:15h) and it worked just fine. Even rendered using the Ultra preset (even though that does not really make a difference in visual fidelity in my case).

I also wanted to try downloading the frame collection, however that crashed octorprint outright (had to ssh in to restart the service), so that's a bit weird. I could not find anything in the main octoprint logs either.

One other thing I noticed is, that some video players can't actually play the resulting file.
MPV and VLC work fine, and I can transcode it using HandBrake, but when trying to play it in octoprint directly, using OctoApp or sharing via Signal or WhatsApp also does not work. Is this maybe a codec issue?

**Comment by cmuche** [comment] 2023-05-24 17:03
Hi @fischer-felix 
Thanks for your feedback! Good to hear that the rendering issues are now gone! 👍 

The downloading problem sounds really weird... The API endpoint just delivers the file and shouldn't hold it in memory or something like that. Can you see a memory usage increase when trying to download? I'll try to reproduce this on my Raspberry as well.

Unfortunately I was also not able to really reproduce your second issue with WhatsApp. Sharing works at least on my phone:
![image](https://github.com/cmuche/octoprint-timelapseplus/assets/14235338/f0892381-de0e-48fb-b22e-d808971b4b1b)

But there were some playback issues in the past. Some browsers won't play some formats. But at least WEBM seemed to work in every browser. But you're right: I just tested it on my iPhone's Safari and it doesn't play anything. So I suspect I have to dig deeper at this topic. Which browser and OS are you using?

**Comment by fischer-felix** [comment] 2023-05-24 17:18
On the desktop I'm using Firefox and Arch Linux, and Android 9 / 13 on my Phone / Tablet.
Tried downloading and at least the Samsung gallery app also won't play it back while mpv on Android works.

**Comment by cmuche** [comment] 2023-05-24 21:21
Yeah, I experienced that Firefox is more picky regarding video formats than other browsers. Unfortunately I don't have an Android device on hand but I could imagine it's a good start if it runs on my mobile Safari. I'll let you know if I can come up with a fix for that 👍🏻

**Comment by cmuche** [comment] 2023-05-25 10:31
Hi @fischer-felix 
Just played around with different pixel formats and came up with a solution that now works in my Firefox as well as on my phone. Maybe you could verify that a) the `test-old.mp4` doesn't work for you as well and b) the `test-new.mp4` does? Would appreciate it very much... Thank you in advance 😃 


https://github.com/cmuche/octoprint-timelapseplus/assets/14235338/4d402aae-7217-41f0-b624-a0ba23092678


https://github.com/cmuche/octoprint-timelapseplus/assets/14235338/a386c9c3-83ea-4749-9ac2-b77f4a40df61

**Comment by fischer-felix** [comment] 2023-05-25 19:10
Yup, only the new one loads, even in this issue (see screenshot below). Also tried it on Android, same result there, so the pixelformat seems to be the cause.
![Screenshot_2023 05 25_21:09:19](https://github.com/cmuche/octoprint-timelapseplus/assets/65448408/9217170d-cd34-488b-b558-185c2b2c54af)

**Comment by cmuche** [comment] 2023-05-25 19:19
GREAT! Thank you very much! 😃 
Then I'll include it in v1.3.0. 👍

**Closed** 2023-06-16 12:55 UTC
Labels: feature-request
